tap 'homebrew/cask'

brew 'ack'
brew 'git'
brew 'coreutils'
brew 'grc'
brew 'wget'
brew 'thefuck'
brew 'hub'
brew 'gpg'
brew 'gnupg'
brew 'pinentry-mac'
brew 'rbenv'
brew 'yarn'
brew 'mas'
brew 'pick'
brew 'github/gh/gh'

cask '1password/tap/1password-cli'
cask 'slack'
cask 'phpstorm'
cask 'iterm2'
cask 'vagrant'
cask 'keybase'
cask 'spotify'
cask 'docker'
cask 'imageoptim'
cask 'gitify'
cask 'visual-studio-code'

mas 'Clocks', id: 414554506
mas 'littleipsum', id: 405772121
